jsyl:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: jsyl_ms
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: your_access_key_id
    access-key-secret: your_access_key_secret
    bucket-name: your_bucket_name
  redis:
    host: localhost
    port: 6379
    password: your_redis_password
    database: 10
  wechat:
    appid:
    secret:
